### ISSUE TITLE
MMSIs for Galapagos Box

### ISSUE THREAD

**Issue by KristinaBoerder** [KristinaBoerder/Galapagos-Box#1]
I aim at getting 'days of fishing vessel presence' in the Galapagos box to compare AIS with the IATTC observer data set to see how much more/less vessels are found in the respective data sets. 

The area of interest
6.000000, -97.000000 and 6.000000, -85.000000
-6.000000, -97.000000 and-6.000000, -85.000000

Time period: 2013 (full year)

To start I am looking for a list of MMSIs of vessels in the Galapagos Box area in 2013. How well can you identify fishing vessels in the area/how are you doing it?

**Comment by redhog** [comment]
I don't know if you have access to this table, or a copy of it, but this is the query needed to get this data:

    SELECT
      *
    FROM
      [data_production__source_data__ais__normalized.ORBCOMM]
    where
      timestamp > '2014-01-01 00:00:00'
      and timestamp < '2015-01-01 00:00:00'
      and lat > -6.000000
      and lat < 6.000000
      and lon > -97.000000
      and lon < -85.000000

**Comment by KristinaBoerder** [comment]
Awesome, thanks so much! 
Will get started on the lists today to extract the fishing vessels and then it would be great to get the tracks for the fishing guys! 
Thanks a lot, that was super quick!

**Comment by pwoods25443** [comment]
@KristinaBoerder can you add Bjorn-skytruth to this repo? He has been evaluating fishing vessel days as detected by our fishing algorithm for fishing in Kiribati, and I'd like for him to collaborate closely on this issue as well.

**Comment by KristinaBoerder** [comment]
Sorry for the delay, added Bjorn!

**Comment by pwoods25443** [comment]
@Bjorn-skytruth we need to re-generate 

https://github.com/KristinaBoerder/Galapagos-Box/blob/master/galapagos-all.csv

with all MMSIs in the bbox above, including a count of the number of position reports associated with each MMSI during 2013.

**Comment by KristinaBoerder** [comment]
Regarding the list of "likely fishing" vessels you have uploaded for me for the Galapagos Box (https://github.com/KristinaBoerder/Galapagos-Box/blob/master/galapagos-fishing.csv) - I have manually checked them. Turns out there are quite a lot of reefers in there that seem to be mislabeled in other list or may actually also be fishing. Will look into that a bit further, thought I'd share my list:
https://github.com/KristinaBoerder/Galapagos-Box/blob/master/Galapagos%20Box%20ST%20MMSI%20Ident%20by%20other%20lists%20manually%20checked.csv

**Comment by Bjorn-skytruth** [comment]
I redid the query against the new 2013 tileset

```sql
SELECT unique(mmsi), count(*) FROM [tilesets.pipeline_2015_08_28_17_46_51] 

WHERE latitude > -6 and latitude < 6 and longitude > -97 and longitude < -85

group by mmsi
```

Only 84 mmsi's are returned. One of these, 371401000, is spoofing with simultaneous broadcasts from the fishing vessel Bernardino and the tanker Morning Calm.

I scraped current identification from MarrineTraffic and shared the list below with Kristina. 

| mmsi      | positions | Name                 | IMO     | Callsign | vesselclass    | 
|-----------|-----------|----------------------|---------|----------|----------------| 
| 773000    | 1278      | ADRIANA              | 7124697 | YJSL9    | Fishing Vessel | 
| 10421670  | 1038      | ALETA AZUL           | 8030245 | BCB      | Fishing Vessel | 
| 123111111 | 389       | VENTUARI             |         | YYGZ     | Fishing        | 
| 123450020 | 188       | NAIR II              |         | XCOH     | Fishing        | 
| 123450800 | 73        | CARTADEDECES         |         | XCCB     | Unspecified    | 
| 200000596 | 39        |                      |         |          |                | 
| 200000599 | 157       |                      |         |          |                | 
| 224252000 | 107       |                      |         |          |                | 
| 224523000 | 131       | ROSITA C             | 9210969 | EAHJ     | Fishing Vessel | 
| 224651000 | 519       | AURORA B.            | 9156058 | EAQT     | Fishing Vessel | 
| 224680000 | 196       | ALBATUN TRES         | 9281310 | EADN     | Fishing Vessel | 
| 277249000 | 57        |                      |         |          |                | 
| 338622000 | 67        | JUDIBANA             | 7334280 | WDG5637  | Fishing Vessel | 
| 349052425 | 98        | SAPT0JOE JORGE       |         | HO_2836  | Fishing        | 
| 352419000 | 1250      | TIUNA                | 8102892 | HO2865   | Fishing Vessel | 
| 353770000 | 414       | TXOPITUNA            | 8719310 | 3EYS     | Fishing Vessel | 
| 354622000 | 644       | HORAISAN             | 9607875 | 3FBE     | Tanker         | 
| 355193000 | 516       |                      |         |          |                | 
| 355651000 | 424       | LAUTARO              | 8134663 | HO3357   | Fishing Vessel | 
| 366920020 | 1         | MARTIN CAPTAIN       |         | WDB6210  | Fishing        | 
| 371216000 | 52        |                      |         |          |                | 
| 371224000 | 455       | DIVA MARIA           | 7915917 | 3EBT3    | Fishing Vessel | 
| 371401000 | 278       | MORNING CALM         | 9523811 | 3EVT2    | Lpg Tanker     | 
| 371696000 | 503       | TEMPLARIO1           | 8003216 | HO4221   | Fishing Vessel | 
| 371759000 | 153       | BARAKA               | 8103107 | HO4222   | Fishing Vessel | 
| 371789000 | 150       | JANE IV              | 7915931 | HO4220   | Fishing Vessel | 
| 372880000 | 34        | REINA DE LA PAZ      | 9545792 | 3EFR6    | Fishing Vessel | 
| 412420214 | 30        | FENGCHENG105         |         |          | Fishing        | 
| 412420225 | 8         | ZHOU HONG YUAN 9     |         | BZ8UU    | Fishing        | 
| 412420248 | 7         | PU YUAN 817          |         | 0        | Fishing        | 
| 412420329 | 5         | TANG QUAN            | 8307272 |          | Reefer         | 
| 412420644 | 56        | ZHOU HONG YUAN 7     |         | 0        | Fishing        | 
| 412420645 | 19        | ZHOU HONG YUAN 16    |         | 0        | Fishing        | 
| 412673260 | 4         | DONGYU2016           |         | BKXW2    | Fishing        | 
| 412673370 | 3         | ZHETYANDONG608       |         | BKR03    | Fishing        | 
| 431022000 | 228       | CHOKYU MARU NO.21    | 9167784 | JHPS     | Fishing Vessel | 
| 431154000 | 277       | GOEI MARU NO.68      | 9172923 | JENI     | Fishing Vessel | 
| 431316000 | 85        | KORYO MARU NO.68     | 9189055 | JFFD     | Fishing Vessel | 
| 431395000 | 354       | SUMIYOSHI MARU NO.81 | 9189079 | JCFC     | Fishing Vessel | 
| 431704490 | 333       | DAIKICHI MARU NO.1   | 8921107 | JJVU     | Fishing Vessel | 
| 431704520 | 271       | KOYO MARU NO.7       | 9053476 | JPTE     | Fishing Vessel | 
| 431802000 | 224       | SHOSHIN MARU NO.80   | 9135391 | JQJP     | Fishing Vessel | 
| 431855000 | 48        | KOYOMARU NO.31       |         | JRSJ     | Fishing        | 
| 432346000 | 240       | KINEI MARU NO.138    | 9267053 | JBBL     | Fishing Vessel | 
| 432374000 | 89        | CHOKYUMARUNO12       | 9279472 | JIHM     | Fishing        | 
| 515777000 | 20        | QI HANG              | 8609292 | XUCT6    | Reefer         | 
| 538004806 | 218       |                      |         |          |                | 
| 576262000 | 273       |                      |         |          |                | 
| 576497000 | 48        | ODIN                 | 8907084 | YJRB3    | Trawler        | 
| 576507000 | 271       |                      |         |          |                | 
| 650766201 | 257       |                      |         |          |                | 
| 730015000 | 493       | AMANDA.S             | 8121587 | HJCZ     | Fishing Vessel | 
| 730016000 | 1928      | MARIA ISABEL C       | 7303982 | HJCW     | Fishing Vessel | 
| 730017000 | 1814      | SEA GEM              | 7528001 | HJDA     | Fishing Vessel | 
| 730018000 | 693       | NAZCA                | 9183738 | HJDB     | Fishing Vessel | 
| 730019000 | 4023      | CABO DE HORNOS       | 9050034 | HJDC     | Fishing Vessel | 
| 730048000 | 1890      | ENTERPRISE           | 7720219 |          | Fishing Vessel | 
| 730049000 | 2136      | SANDRA C             | 7366659 | HJSW     | Fishing Vessel | 
| 730050000 | 976       | EL REY               | 7313535 | HJSX     | Fishing Vessel | 
| 730051000 | 496       | AMERICAN EAGLE       | 7508910 | HJSY     | Fishing Vessel | 
| 730052000 | 3045      | GRENADIER            | 7435278 | HKRQ     | Fishing Vessel | 
| 730059000 | 961       | DOMINADOR 1          |         | HKMO     | Unspecified    | 
| 735057501 | 16        |                      |         |          |                | 
| 735057559 | 284       |                      |         |          |                | 
| 735057565 | 1767      | SAN ANDRES           | 8909252 | HC4154   | Fishing Vessel | 
| 735057573 | 279       |                      |         |          |                | 
| 735057587 | 1131      | UGAVI                | 7910682 | HC4385   | Fishing Vessel | 
| 735057638 | 1186      | UGAVI 2              | 8206301 | HC4593   | Fishing Vessel | 
| 735057642 | 83        | MARIELLA             | 8113401 | HC2886   | Fishing Vessel | 
| 735058003 | 619       | PANAMA TUNA          | 9175028 | HC4697   | Fishing Vessel | 
| 735058906 | 482       | ESTHERCHO            | 7207499 | HC5236   | Fishing Vessel | 
| 735058912 | 571       | FLORENTINO           | 9130793 | HC5240   | Fishing Vessel | 
| 735059088 | 370       | GUAYATUNA UNO        | 8107476 | HC4649   | Fishing Vessel | 
| 735059089 | 177       | GUAYATUNA DOS        | 8111087 | HC4650   | Fishing Vessel | 
| 774559424 | 285       | CANAIMA              |         | YYEM     | Fishing        | 
| 775000000 | 2908      | EGIR                 |         | YYV5708  | Tug            | 
| 775602000 | 451       | EMILIO               | 7235628 | HO_4007  | Fishing Vessel | 
| 775610060 | 503       | VENTUARI             | 7407908 | YYGZ     | Fishing Vessel | 
| 775613000 | 14        | AMAZONAS             | 7121138 | YYFB     | Fishing Vessel | 
| 775616000 | 255       | FALCON               | 7395521 | YYCL     | Fishing        | 
| 775626000 | 162       | LA ROSA MASTICA      | 7342304 | YYJV     | Fishing Vessel | 
| 775627000 | 1038      | CAYUDE               | 7601736 | YYEH     | Fishing Vessel | 
| 775628000 | 682       | TAURUS TUNA          | 7230422 | YYEK     | Fishing Vessel | 
| 800810001 | 27        | RONG CHANG NO1       |         | 3X-2025  | Fishing        |
